name: Lint and Test

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests
        run: node --experimental-vm-modules node_modules/jest/bin/jest.js
        working-directory: ./backend
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  frontend-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn --silent
          start: yarn dev
          wait-on: 'http://localhost:8080'
          working-directory: ./frontend
        env:
          # Set test environment variables for frontend
          # Point API calls to the frontend server since tests use mocked APIs
          NEXT_PUBLIC_API_URL: http://localhost:8080
          NEXT_PUBLIC_SOCKET_URL: http://localhost:8080
          NEXT_PUBLIC_FRONTEND_URL: http://localhost:8080
          NEXTAUTH_URL: http://localhost:8080
          NEXTAUTH_SECRET: test-secret
          GOOGLE_CLIENT_ID: test-client-id
          GOOGLE_CLIENT_SECRET: test-client-secret
          NODE_ENV: test
        timeout-minutes: 15
